import pymel.core as pm


def applyShapes(shp_dict):
    for jnt, xforms in shp_dict.items():
        jntobj = pm.ls(jnt)
        if jntobj:
            j = jntobj[0]
            j.setTranslation(xforms['t'])
            j.setRotation(xforms['r'])
            j.setScale(xforms['s'])


def vecToList(x):
    return list(round(v, 4) for v in x)


def getShapes(jntnames):
    out = {}
    for jnt in jntnames:
        if pm.ls(jnt):
            jntobj = pm.ls(jnt)[0]
            xfs = {'t': vecToList(jntobj.getTranslation()),
                   'r': vecToList(jntobj.getRotation()),
                   's': vecToList(jntobj.getScale())}
            out[jnt] = xfs

    return out


HEAD_JNTS = ['cf_J_FaceRoot',
             'cf_J_FaceBase',
             'cf_J_FaceLowBase',
             'cf_J_FaceLow_s',
             'cf_J_CheekLow_L',
             'cf_J_CheekLow_R',
             'cf_J_CheekUp_L',
             'cf_J_CheekUp_R',
             'cf_J_Chin_rs',
             'cf_J_ChinTip_s',
             'cf_J_ChinLow',
             'cf_J_MouthBase_tr',
             'cf_J_MouthBase_s',
             'cf_J_MouthMove',
             'cf_J_Mouth_L',
             'cf_J_Mouth_R',
             'cf_J_MouthLow',
             'cf_J_Mouthup',
             'cf_J_MouthCavity',
             'cf_J_FaceUp_ty',
             'cf_J_EarBase_s_L',
             'cf_J_EarLow_L',
             'cf_J_EarUp_L',
             'cf_J_EarBase_s_R',
             'cf_J_EarLow_R',
             'cf_J_EarUp_R',
             'cf_J_FaceUp_tz',
             'cf_J_Eye_t_L',
             'cf_J_Eye_s_L',
             'cf_J_Eye_r_L',
             'cf_J_Eye01_L',
             'cf_J_Eye01_s_L',
             'cf_J_Eye02_L',
             'cf_J_Eye02_s_L',
             'cf_J_Eye03_L',
             'cf_J_Eye03_s_L',
             'cf_J_Eye04_L',
             'cf_J_Eye04_s_L',
             'cf_J_EyePos_rz_L',
             'cf_J_look_L',
             'cf_J_eye_rs_L',
             'cf_J_pupil_s_L',
             'cf_J_Eye_t_R',
             'cf_J_Eye_s_R',
             'cf_J_Eye_r_R',
             'cf_J_Eye01_R',
             'cf_J_Eye01_s_R',
             'cf_J_Eye02_R',
             'cf_J_Eye02_s_R',
             'cf_J_Eye03_R',
             'cf_J_Eye03_s_R',
             'cf_J_Eye04_R',
             'cf_J_Eye04_s_R',
             'cf_J_EyePos_rz_R',
             'cf_J_look_R',
             'cf_J_eye_rs_R',
             'cf_J_pupil_s_R',
             'cf_J_Mayu_L',
             'cf_J_MayuMid_s_L',
             'cf_J_MayuTip_s_L',
             'cf_J_Mayu_R',
             'cf_J_MayuMid_s_R',
             'cf_J_MayuTip_s_R',
             'cf_J_NoseBase_trs',
             'cf_J_NoseBase_s',
             'cf_J_Nose_r',
             'cf_J_Nose_t',
             'cf_J_Nose_tip',
             'cf_J_NoseWing_tx_L',
             'cf_J_NoseWing_tx_R',
             'cf_J_NoseBridge_t',
             'cf_J_NoseBridge_s',
             'cf_J_FaceRoot_s']

BODY_JNTS = ['cf_J_Mune_Nip02_s_L',
             'cf_J_Spine01_s',
             'cf_J_Hand_s_L',
             'cf_J_Mune_Nip01_s_L',
             'cf_J_Mune00_t_L',
             'cf_J_ArmElbo_low_s_R',
             'cf_J_LegKnee_s_R',
             'cf_J_Spine02_s',
             'cf_J_ArmLow02_s_L',
             'cf_J_Siri_s_R',
             'cf_J_ArmLow02_s_R',
             'cf_J_LegKnee_s_L',
             'cf_J_ArmElbo_low_s_L',
             'cf_J_Spine03_s',
             'cf_J_Head_s',
             'cf_J_sk_top_s',
             'cf_J_Mune00_t_R',
             'cf_J_Hand_s_R',
             'cf_N_height',
             'cf_J_LegUpDam_s_L',
             'cf_J_Mune_Nip01_s_R',
             'cf_J_ArmUp03_s_R',
             'cf_J_ArmUp02_s_R',
             'cf_J_ArmLow01_s_L',
             'cf_J_Mune_Nipacs01_R',
             'cf_J_LegKnee_low_s_L',
             'cf_J_Mune_Nipacs01_L',
             'cf_J_LegKnee_low_s_R',
             'cf_J_Kosi01_s',
             'cf_J_Mune04_s_L',
             'cf_J_Mune_Nip02_s_R',
             'cf_J_LegKnee_back_s_L',
             'cf_J_ArmLow01_s_R',
             'cf_J_ArmUp03_s_L',
             'cf_J_ArmUp02_s_L',
             'cf_J_LegLow03_s_L',
             'cf_J_Shoulder02_s_L',
             'cf_J_Mune02_s_R',
             'cf_J_Mune03_s_R',
             'cf_J_Mune00_s_L',
             'cf_J_Mune01_s_L',
             'cf_J_Mune01_t_R',
             'cf_J_Mune00_d_R',
             'cf_J_Kosi02_s',
             'cf_J_Hand_Wrist_s_R',
             'cf_J_Mune02_t_L',
             'cf_J_LegUp01_s_L',
             'cf_J_Mune01_t_L',
             'cf_J_Mune00_d_L',
             'cf_J_Siri_s_L',
             'cf_J_Mune00_s_R',
             'cf_J_Mune01_s_R',
             'cf_J_LegKnee_back_s_R',
             'cf_J_Mune02_s_L',
             'cf_J_Mune03_s_L',
             'cf_J_LegLow03_s_R',
             'cf_J_Shoulder02_s_R',
             'cf_J_LegLow02_s_L',
             'cf_J_LegUp03_s_L',
             'cf_J_LegUp02_s_L',
             'cf_J_LegUp01_s_R',
             'cf_J_ArmUp01_s_L',
             'cf_J_Mune02_t_R',
             'cf_J_Hand_Wrist_s_L',
             'cf_J_LegLow01_s_L',
             'cf_J_Neck_s',
             'cf_J_ArmElbo_up_s_R',
             'cf_J_Shoulder_s_R',
             'cf_J_Shoulder_s_L',
             'cf_J_ArmElbo_up_s_L',
             'cf_J_LegLow01_s_R',
             'cf_J_ArmUp01_s_R',
             'cf_J_Mune04_s_R',
             'cf_J_LegUp03_s_R',
             'cf_J_LegUp02_s_R',
             'cf_J_LegUpDam_s_R',
             'cf_J_LegLow02_s_R']
